birdcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.home, name='home'),
	path('about/', views.about, name='about'),
	path('birds/', views.birds_index, name='index'),
	path('birds/<int:bird_id>/', views.birds_detail, name='detail'),
	path('birds/create/', views.BirdCreate.as_view(), name='birds_create'),
	path('birds/<int:pk>/update/', views.BirdUpdate.as_view(), name='birds_update'),
	path('birds/<int:pk>/delete/', views.BirdDelete.as_view(), name='birds_delete'),
	path('birds/<int:bird_id>/add_feeding/', views.add_feeding, name='add_feeding'),
	path('birds/<int:bird_id>/add_photo/', views.add_photo, name='add_photo'),
	path('birds/<int:bird_id>/assoc_toy/<int:toy_id>/', views.assoc_toy, name='assoc_toy'),
	path('birds/<int:bird_id>/unassoc_toy/<int:toy_id>/', views.unassoc_toy, name='unassoc_toy'),
	path('toys/', views.ToyIndex.as_view(), name='toys_index'),
	path('toys/<int:pk>/', views.ToyDetail.as_view(), name='toys_detail'),
	path('toys/create/', views.ToyCreate.as_view(), name='toys_create'),
	path('toys/<int:pk>/update/', views.ToyUpdate.as_view(), name='toys_update'),
	path('toys/<int:pk>/delete/', views.ToyDelete.as_view(), name='toys_delete'),
	path('accounts/signup/', views.signup, name='signup'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User

MEALS = (
    ('B', 'Breakfast'),
    ('L', 'Lunch'),
    ('D', 'Dinner')
)

# Create your models here.
class Toy(models.Model):
    name = models.CharField(max_length=50)
    color = models.CharField(max_length=20)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('toys_detail', kwargs={'pk': self.id})


class Bird(models.Model):
    name = models.CharField(max_length=100)
    species = models.CharField(max_length=100)
    description = models.TextField()
    age = models.IntegerField()
    toys = models.ManyToManyField(Toy)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'bird_id': self.id})
    
    def fed_for_today(self):
        return self.feeding_set.filter(date=date.today()).count() >= len(MEALS)


class Feeding(models.Model):
    date = models.DateField('Feeding Date')
    meal = models.CharField(
        max_length=1,
        choices=MEALS,
        default=MEALS[0][0],
    )
    bird = models.ForeignKey(Bird, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_meal_display()} on {self.date}"
    
    class Meta:
        ordering = ['-date']


class Photo(models.Model):
    url = models.CharField(max_length=200)
    bird = models.ForeignKey(Bird, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for bird_id: {self.bird_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Feeding

class FeedingForm(ModelForm):
    class Meta:
        model = Feeding
        fields = ['date', 'meal']

main_app/views.py
import uuid
import os
import boto3
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Bird, Toy, Photo
from .forms import FeedingForm

# Create your views here.
def home(request):
    return render(request, 'home.html')


def about(request):
    return render(request, 'about.html')


@login_required
def birds_index(request):
    birds = Bird.objects.filter(user=request.user)
    return render(request, 'birds/index.html', { 'birds': birds })


@login_required
def birds_detail(request, bird_id):
    bird = Bird.objects.get(id=bird_id)
    # Get the id's of the toys that are already associated with the bird:
    id_list = bird.toys.all().values_list('id')
    # Get the toys that are not associated with the bird:
    toys_bird_doesnt_have = Toy.objects.exclude(id__in=id_list)
    feeding_form = FeedingForm()
    return render(request, 'birds/detail.html', {
        'bird': bird,
        'feeding_form': feeding_form,
        'toys': toys_bird_doesnt_have
    })


@login_required
def add_feeding(request, bird_id):
    form = FeedingForm(request.POST)
    if form.is_valid():
        new_feeding = form.save(commit=False)
        new_feeding.bird_id = bird_id
        new_feeding.save()
    return redirect('detail', bird_id=bird_id)


@login_required
def add_photo(request, bird_id):
    # 'photo-file' will be the name of the input field in the form,
    #   return None if it doesn't exist:
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        # Create a unique 'key' for S3, needs file extension too:
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        # Wrap in a try/except block to handle errors:
        try:
            bucket = os.environ['S3_BUCKET']
            s3.upload_fileobj(photo_file, bucket, key)
            # Build the full URL for the photo:
            url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
            # Add the photo to the database (use bird_id from the URL):
            # Note: using bird_id from the URL, not the bird object saves a DB query:
            Photo.objects.create(url=url, bird_id=bird_id)
        except Exception as e:
            print('An error occurred uploading file to S3')
            print(e)
    return redirect('detail', bird_id=bird_id)


class BirdCreate(LoginRequiredMixin, CreateView):
    model = Bird
    fields = ['name', 'species', 'description', 'age']

    # Override the inherited method called when a valid form is submitted:
    def form_valid(self, form):
        # Assign the logged in user (self.request.user) to the bird (form.instance):
        form.instance.user = self.request.user
        # Pass control back to the superclass CreateView's form_valid() method to do its job:
        return super().form_valid(form)


class BirdUpdate(LoginRequiredMixin, UpdateView):
    model = Bird
    fields = ['species', 'description', 'age']


class BirdDelete(LoginRequiredMixin, DeleteView):
    model = Bird
    success_url = '/birds'


class ToyIndex(LoginRequiredMixin, ListView):
    model = Toy


class ToyDetail(LoginRequiredMixin, DetailView):
    model = Toy


class ToyCreate(LoginRequiredMixin, CreateView):
    model = Toy
    fields = '__all__'


class ToyUpdate(LoginRequiredMixin, UpdateView):
    model = Toy
    fields = ['name', 'color']


class ToyDelete(LoginRequiredMixin, DeleteView):
    model = Toy
    success_url = '/toys'


@login_required
def assoc_toy(request, bird_id, toy_id):
    Bird.objects.get(id=bird_id).toys.add(toy_id)
    return redirect('detail', bird_id=bird_id)


@login_required
def unassoc_toy(request, bird_id, toy_id):
    Bird.objects.get(id=bird_id).toys.remove(toy_id)
    return redirect('detail', bird_id=bird_id)


def signup(request):
    error_message = ''
    if request.method == 'POST':
        # Create a UserCreationForm instance using the data from the request:
        form = UserCreationForm(request.POST)
        if form.is_valid():
            # Save the form to the database:
            user = form.save()
            # Log the user in:
            login(request, user)
            return redirect('index')
        else:
            # If the form is not valid, set the error message:
            error_message = 'Invalid sign up - try again'
    # If the request method is GET, or the sign up fails, render signup.html with an empty form:
    form = UserCreationForm()
    context = { 'form': form, 'error': error_message }
    return render(request, 'registration/signup.html', context)

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

  <h1>About the Bird Collector</h1>
  <hr>
  <p>Hire the Bird Collector!</p>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Bird Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="{% url 'home' %}" class="left brand-logo">&nbsp;&nbsp;Bird Collector</a></li>
        </ul>
        <ul class="right">
          {% if user.is_authenticated %}
            <li style="margin-right: 15px;">Hello, {{ user.username }}</li>
          {% endif %}
          <li><a href="{% url 'about' %}">About</a></li>
          {% if user.is_authenticated %}
            <li><a href="{% url 'toys_create' %}">Add a Toy</a></li>
            <li><a href="{% url 'toys_index' %}">View All Toys</a></li>
            <li><a href="{% url 'birds_create' %}">Add a Bird</a></li>
            <li><a href="{% url 'index' %}">View All My Birds</a></li>
            <li>
              <form method="POST" action="{% url 'logout' %}">
                {% csrf_token %}
                <button type="submit" id="logout-btn">Log Out</button>
              </form>
            </li>
            {% else %}
            <li><a href="{% url 'signup' %}">Sign Up</a></li>
            <li><a href="{% url 'login' %}">Log In</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2025 Bird Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/birds/detail.html
{% extends 'base.html' %}
{% block content %}

  <h1>Bird Details</h1>

  <div class="row">
    <div class="col s6">
      <div class="card">
        <div class="card-content">
          <span class="card-title">{{ bird.name }}</span>
          <p>Species: {{ bird.species }}</p>
          <p>Description: {{ bird.description|linebreaks }}</p>
          {% if bird.age > 0 %}
            <p>Age: {{ bird.age }}</p>
          {% else %}
            <p>Age: Chick</p>
          {% endif %}
        </div>
        <div class="card-action">
          <a href="{% url 'birds_update' bird.id %}">Edit</a>
          <a href="{% url 'birds_delete' bird.id %}">Delete</a>
        </div>
      </div>
      {% for photo in bird.photo_set.all %}
        <img class="responsive-img card-panel" src="{{photo.url}}">
      {% empty %}
        <div class="card-panel teal-text center-align">No Photos Uploaded</div>
      {% endfor %}
      <form action="{% url 'add_photo' bird.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
        {% csrf_token %}
        <input type="file" name="photo-file">
        <br><br>
        <button type="submit" class="btn">Upload Photo</button>
      </form>    
    </div>
    <div class="col s6">
      <form action="{% url 'add_feeding' bird.id %}" method="POST">
        {% csrf_token %}
        <!-- Render the inputs -->
        {{ feeding_form.as_p }}
        <input type="submit" class="btn" value="Add Feeding">
      </form>
      <br>
      {% if bird.fed_for_today %}
        <div class="card-panel teal-text center-align">{{bird.name}} has been fed all meals for today</div>
      {% else %}
        <div class="card-panel red-text center-align">{{bird.name}} might be hungry</div>
      {% endif %}
      <table class="striped">
        <thead>
          <tr><th>Date</th><th>Meal</th></tr>
        </thead>
        <tbody>
          {% for feeding in bird.feeding_set.all %}
            <tr>
              <td>{{feeding.date}}</td>
              <td>{{feeding.get_meal_display}}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>

  <hr>
  <div class="row">
    <div class="col s6">
      <h3>{{ bird.name }}'s Toys</h3>
      {% if bird.toys.count %}
        {% for toy in bird.toys.all %}
          <div class="card">
            <div class="card-content">
              <span class="card-title">
                A <span style="color: {{ toy.color }}">{{ toy.color }}</span> {{ toy.name }}
              </span>
            </div>
            <div class="card-action">
              <form action="{% url 'unassoc_toy' bird.id toy.id %}" method="POST">
                {% csrf_token %}
                <button type="submit" class="btn">Remove</button>
              </form>
            </div>
          </div>
        {% endfor %}
      {% else %}
        <h5>No Toys 😿</h5>
      {% endif %}
    </div>
    <div class="col s6">
      <h3>Available Toys</h3>
      {% if toys.count %}
        {% for toy in toys.all %}
          <div class="card">
            <div class="card-content">
              <span class="card-title">
                A <span style="color: {{ toy.color }}">{{ toy.color }}</span> {{ toy.name }}
              </span>
            </div>
            <div class="card-action">
              <form action="{% url 'assoc_toy' bird.id toy.id %}" method="POST">
                {% csrf_token %}
                <button type="submit" class="btn">Add</button>
              </form>
            </div>
          </div>
        {% endfor %}
      {% else %}
        <h5>{{bird.name}} Already Has All Toys Available</h5>
      {% endif %}
    </div>    
  </div>

<script>
  const dateEl = document.getElementById('id_date');
  // M is Materialize's global variable
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });
  const selectEl = document.getElementById('id_meal');
  M.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/birds/index.html
{% extends 'base.html' %}
{% block content %}

  <h1>Bird List</h1>

  {% for bird in birds %}
  <div class="card">
    <a href="{% url 'detail' bird.id %}">
      <div class="card-content">
        <span class="card-title">{{ bird.name }}</span>
        <p>Species: {{ bird.species }}</p>
        <p>Description: {{ bird.description|linebreaks }}</p>
        {% if bird.age > 0 %}
          <p>Age: {{ bird.age }}</p>
        {% else %}
          <p>Age: Chick</p>
        {% endif %}
      </div>
    </a>
  </div>
{% endfor %}

{% endblock %}

main_app/templates/home.html
{% extends "base.html" %}
{% block content %}

  <h1>Home Page</h1>

{% endblock %}

main_app/templates/main_app/bird_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

  <h1>Delete Bird</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' bird.id %}">Cancel</a>
  </form>

{% endblock %}

main_app/templates/main_app/bird_form.html
{% extends 'base.html' %}
{% block content %}

  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Bird</h1>
  {% endif %}

  <form action="" method="POST">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>

{% endblock %}

main_app/templates/main_app/toy_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

  <h1>Delete Toy</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'toys_detail' toy.id %}">Cancel</a>
  </form>

{% endblock %}

main_app/templates/main_app/toy_detail.html
{% extends 'base.html' %}
{% block content %}

  <h1>Toy Details</h1>

  <div class="row">
    <div class="col s6">
      <div class="card">
        <div class="card-content">
          <span class="card-title">{{ toy.name }}</span>
          <p>Color: {{ toy.color }}</p>
        </div>
        <div class="card-action">
          <a href="{% url 'toys_update' toy.id %}">Edit</a>
          <a href="{% url 'toys_delete' toy.id %}">Delete</a>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

main_app/templates/main_app/toy_form.html
{% extends 'base.html' %}
{% block content %}

  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Toy</h1>
  {% endif %}

  <form action="" method="POST">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>

{% endblock %}

main_app/templates/main_app/toy_list.html
{% extends 'base.html' %}
{% block content %}

  <h1>Toy List</h1>

  {% for toy in toy_list %}
  <div class="card">
    <a href="{% url 'toys_detail' toy.id %}">
      <div class="card-content">
        <span class="card-title">{{ toy.name }}</span>
        <p>Color: {{ toy.color }}</p>
      </div>
    </a>
  </div>
{% endfor %}

{% endblock %}